spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException,缺省:30秒
      connectionTimeout: 30000
      #一个连接空闲状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idleTimeout: 600000
      #一个连接的最大生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，
      maxLifetime: 1800000
      maximumPoolSize: 3
      minimumIdle: 1
  ai:
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: my-rag
        initialize-schema: true
        use-tls: false
        api-key: RzxqVXK11CDKl1Bt
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3.5:cloud
      embedding:
        options:
          model: nomic-embed-text
iep:
  url: https://home.raiep.cn/iepback