server:
  port: 8888
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
system:
  ai:
    topKPerQuery: 5      # 每个rag查询变体检索文档数量
    allTopK: 20           # 所有rag查询变体检索文档总数量
    numVariants: 5        # rag查询变体数量
    similarityThreshold: 0.65 # rag查询相似度阈值
mybatis-plus:
  mapper-locations: classpath:/mapper/*
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
